name: Continuous integration
on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Check out CSL repos
        run: |
          cd ..
          git clone --depth 1 https://github.com/citation-style-language/styles
          git clone --depth 1 https://github.com/citation-style-language/locales
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
      - run: cargo test --no-default-features
      - run: cargo test --all-features

  checks:
    name: Check clippy, formatting, and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets
      - run: cargo fmt --check --all
      - run: cargo doc --no-deps
